### ISSUE TITLE
Weird things can happen with email addresses

### ISSUE THREAD

**Issue by pjf** [pjf/idonethis-perl#11]
Apparently one can login using an email address instead of a username.  Our code is not expecting this.  Either:
1. Detect attempts to login by email address and die noisily (asking for username).
2. Fix the code to be email address friendly.

**Comment by wizonesolutions** [comment]
Re. point 2, I think the code is username-friendly already? :P

**Comment by pjf** [comment]
D'oh. I meant email-address friendly. :)  Fixing description now.
