### ISSUE TITLE
Implement basic search interface or range querying

### ISSUE THREAD

**Issue by wizonesolutions** [pjf/idonethis-perl#12]
I use iDoneThis to keep track of what I did last on the various projects I juggle. Sometimes I last juggled particular projects on days before yesterday and don't remember exactly which. I'd love a way to enter a range of dates and just see all the dones dumped from that timeframe. In **fact**, when I think about it now, what I'd love is this date-range functionality because then I could just `grep` after what I'm looking for. If I need better search, I can open a web browser and do it on iDoneThis. But normally I don't need really good search, just something to `grep`.

It'd be a plus if when in date-range mode every task could be prefixed with the datestamp.

Theoretical invocation and output:

`idone -r -s "four days ago" -e "today"

2013-03-18: Did some awesome stuff.
....
2013-03-22: Posted new issue to pfenwick/idonethis-perl.`

There is probably a neater way to format the command. Maybe just `-r "four days ago,today"`. But I think the underlying meaning of my request is conveyed :)

**Comment by pjf** [comment]
It so happens that IDT only provides a date-range interface, and WebService::Idonethis is providing a stripped-down version that sets the start and end dates to the same day.

So, the steps to make this happen are:
- [x] Write a `get_range` method for WS::IDT
- [x] Reimplement `get_day` in terms of `get_range`
- [x] Update `idone` to provide ranged searches.
- [x] Have `idone` display dates when a ranged search is performed.
- [x] Figure out what to do if one is trying to _add_ a done on a ranged search. (Probably throw an error.)

Personally I like `-r start,end` (and of course these should allow human-readable dates).

**Comment by wizonesolutions** [comment]
Agree with everything.
On Mar 22, 2013 11:31 AM, "Paul Fenwick" notifications@github.com wrote:

It so happens that IDT only provides a date-range interface, and
WebService::Idonethis is providing a stripped-down version that sets the
start and end dates to the same day.

So, the steps to make this happen are:
-  Write a get_range method for WS::IDT
-  Reimplement get_day in terms of get_range
-  Update idone to provide ranged searches.
-  Have idone display dates when a ranged search is performed.
-  Figure out what to do if one is trying to _add_ a done on a ranged
  search. (Probably throw an error.)

Personally I like -r start,end (and of course these should allow
human-readable dates).

—
Reply to this email directly or view it on
GitHubhttps://github.com/pjf/idonethis-perl/issues/12#issuecomment-15290039
.

**Comment by pjf** [comment]
Okay, this is done. :)

```
$ idone -r '1 week ago, today'

[2013-03-15] Chatted with Emma Jane. Mainly about Klingon.
[2013-03-16] Found $20 on my desk. Now I can't find my wallet.
[2013-03-18] Signed up for HabitRPG. I think this has potential.
[2013-03-19] Coded WebService::HabitRPG
[2013-03-19] Found pianobar sucks when you have a shitty network.
[2013-03-21] Went to swing dancing in Nth Melb.
```

v0.17 is headed to the CPAN now, or you can use the changes in the git repo if you're impatient. :)

**Comment by pjf** [comment]
Oh, and be nice with the range searches. I'm pretty sure idonethis don't actually put any restrictions on date ranges. :)

**Comment by pjf** [comment]
And just because I'm exceptionally proud of my command-line right now, I logged this with:

`hrpg + issue -l "Added range support to idone"`

and gained XP on HabitRPG, added this to my list of completed tasks, and listed all tasks I've done today. :)

**Comment by wizonesolutions** [comment]
Yep, it's working well, and I can grep for the stuff I want. Thanks!
