### ISSUE TITLE
Make range-querying easier when end date is today (single-argument -r)

### ISSUE THREAD

**Issue by wizonesolutions** [pjf/idonethis-perl#13]
Would be great to be able to just do `idone -r -7d` and have it mean `idone -r '-7d,0d'`. Tasks within the last week.

For extra extra credit, make that the default behavior of the `-r` switch.

In summary, range-querying goes from one to three modes of behavior:

Two arguments: Same as now.
One argument: Assume range is between first `-r` argument and `now`.
Zero arguments: Assume range is between one week ago and now.

**Comment by pjf** [comment]
I love this idea.  Zero arguments may be a little tricky due to the underlying tech and my laziness, but the one argument is easy and perfect!

**Comment by pjf** [comment]
Released as v0.08.
