### ISSUE TITLE
Allow adding[/listing] dones for specific day

### ISSUE THREAD

**Issue by wizonesolutions** [pjf/idonethis-perl#4]
Similar to `-y`, but allow specifying a date (OK if it has to be ISO-8601 format).

Would be nice if the date switch also worked for `-l`.

**Comment by pjf** [comment]
This is done.  The switch is `-d` and you can chain them.  For example, the command below lists what you did on new years day 2012, and allows you to input new dones for that date.

`idone -lcd 2012-01-01`
