### ISSUE TITLE
Allow fuzzy/natural-language dates

### ISSUE THREAD

**Issue by wizonesolutions** [pjf/idonethis-perl#9]
Today I wanted to check what I had done "last Friday." So then I was like, oh wait, what was last Friday's date? Umm...oh, March 8. You know, why can't I just use `-d "last Friday"`? pfenwick is smart. I bet he can add this in like 10 minutes. Let us open a self-referencing GitHub issue.

**Comment by pjf** [comment]
Yeah, I want this too. :)

**Comment by pjf** [comment]
Done!  You can now enjoy this in 0.15.  Date formats include lovely things like:

`last thursday`
`three days ago`
`second tuesday in june 2012`

I'm using `Date::Manip::Date` for parsing (yes, this is an extra dependency), and it's pretty darn clever.  If you give it a date that it doesn't understand, you'll get an obvious error.

Enjoy!
